//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBhecsa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventariosProducto
    {
        public int InventarioProducto { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<int> Utilidad { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public System.Guid ProductoID { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
