//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBhecsa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatosHECSAEntities : DbContext
    {
        public DatosHECSAEntities()
            : base("name=DatosHECSAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CorreoNotificacion> CorreoNotificacions { get; set; }
        public virtual DbSet<DatosFiscale> DatosFiscales { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<Genero> Generos { get; set; }
        public virtual DbSet<InventariosProducto> InventariosProductos { get; set; }
        public virtual DbSet<MexCP> MexCPs { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<Proveedore> Proveedores { get; set; }
        public virtual DbSet<ProveedoresContacto> ProveedoresContactos { get; set; }
        public virtual DbSet<RolesUsuario> RolesUsuarios { get; set; }
        public virtual DbSet<TiposProveedore> TiposProveedores { get; set; }
        public virtual DbSet<TiposUbicacione> TiposUbicaciones { get; set; }
        public virtual DbSet<TiposUsuario> TiposUsuarios { get; set; }
        public virtual DbSet<Ubicacione> Ubicaciones { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
