//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBhecsa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedores()
        {
            this.ProveedoresContactos = new HashSet<ProveedoresContactos>();
        }
    
        public System.Guid ProveedoresID { get; set; }
        public Nullable<int> TipoProveedorID { get; set; }
        public string NombresRS { get; set; }
        public string CorreoElectronico { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.Guid> UbicacionID { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int EstatusRegistroID { get; set; }
        public System.Guid EmpresaID { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual TiposProveedores TiposProveedores { get; set; }
        public virtual Ubicaciones Ubicaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProveedoresContactos> ProveedoresContactos { get; set; }
    }
}
