//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBhecsa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedoresContacto
    {
        public System.Guid ProveedorContactoID { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string CorreoPersonal { get; set; }
        public string CorreInstitucional { get; set; }
        public string TelefonoContacto { get; set; }
        public string Celular { get; set; }
        public Nullable<System.Guid> UbicacionID { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int EstatusRegistroID { get; set; }
        public System.Guid ProveedoresID { get; set; }
    
        public virtual Proveedore Proveedore { get; set; }
    }
}
