//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBhecsa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedore()
        {
            this.ProveedoresContactos = new HashSet<ProveedoresContacto>();
        }
    
        public System.Guid ProveedoresID { get; set; }
        public Nullable<int> TipoProveedorID { get; set; }
        public string NombresRS { get; set; }
        public string CorreoElectronico { get; set; }
        public string Telefono { get; set; }
        public int EmpresaID { get; set; }
        public Nullable<System.Guid> UbicacionID { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int EstatusRegistroID { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual TiposProveedore TiposProveedore { get; set; }
        public virtual Ubicacione Ubicacione { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProveedoresContacto> ProveedoresContactos { get; set; }
    }
}
