//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBhecsa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public System.Guid UsuarioID { get; set; }
        public int RolUsuarioID { get; set; }
        public int TipoUsuarioID { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> GeneroID { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Usuario1 { get; set; }
        public string Clave { get; set; }
        public string CodigoUsuario { get; set; }
        public string CorreoPersonal { get; set; }
        public string CorreInstitucional { get; set; }
        public string TelefonoContacto { get; set; }
        public string Celular { get; set; }
        public Nullable<System.Guid> UbicacionID { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int EstatusRegistroID { get; set; }
        public string Token { get; set; }
        public int EmpresaID { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual RolesUsuario RolesUsuario { get; set; }
        public virtual TiposUsuario TiposUsuario { get; set; }
        public virtual Ubicacione Ubicacione { get; set; }
    }
}
